### ISSUE TITLE
asizeof does not properly size Shapely geometries

### ISSUE THREAD

**Issue by kannes** [pympler/pympler#101]
Now I don't know if "C objects" are in scope of this wonderful project but since numpy is explicitly mentioned I thought I could really use it on any other module.

I would love to use it for some memory investigations in a project using the https://github.com/Toblerity/Shapely module. *From what I know* that uses GEOS in the background which is a C library. 

```
>>> from pympler import asizeof
>>> from shapely.geometry import Point, MultiPoint
>>> point = Point(0, 0)
>>> asizeof.asizeof(point)
440
>>> many_points = [Point(0, 0) for _ in range(1000)]
>>> asizeof.asizeof(many_points)
209264
>>> multipoint = MultiPoint(many_points)  # aggregate the 1000 points in one multi-geometry
>>> asizeof.asizeof(multipoint)
440
```

The actual memory used for the `multipoint` object should be closer to the size of the `many_points` object. It definitely can't be 440 bytes.

**Comment by mrJean1** [comment]
Unfortunately, `asizeof` only sizes Python objects and their attributes.  The `Multipoint` object (and probably most other objects) in the `shapely` package are just proxies (based on `ctypes`) around objects in some external, non-Python library which are not sizable by `asizeof`.

**Comment by kannes** [comment]
Ah, that makes sense. Maybe there is something built into Shapely or GEOS that one could use. cc @sgillies?

**Comment by sgillies** [comment]
There is not. You would have to estimate it: 2-3 C doubles per coordinate plus the base size of the GEOS geometry structure.

**Comment by kannes** [comment]
I looked at the `asizeof` code and it is too complex for me to try this. I'll just write me some hacky function on my own, that will be enough for my use case.

Many thanks for the swift feedback to you two!
