### ISSUE TITLE
Feature Request: Skip all objects of type

### ISSUE THREAD

**Issue by Bootstrap360** [pympler/pympler#127]
The issue: I am trying to navigate the memory of a complex object to find large blocks of memory such as a list containing many or large objects. However, logging.Logger objects show up as massive objects while using  `asizeof.asized(generator, detail=2).format()`.

What I would like to be able to do is to completely ignore objects of type logging.Logger.

What I have tried:

`asizeof._getsizeof_excls_add(logging.Logger)`

This behavior skips trying to measure the sys.getsizeof this object but continues down it's reference tree. I would like it to skip these objects and ignore them all together.

Example code:

``` python
import logging


class MyObject:
    def __init__(self):
        self.some_large_list = ([1] * 1000,)
        self.anotherlist = ([1] * 5,)
        self.logger = logging.getLogger()


large_object = MyObject()
asizeof._getsizeof_excls_add(logging.Logger)
print(asizeof.asized(large_object, detail=2).format())
```

Current output

```
<.MyObject object at 0x7fa671aa2710> size=769448 flat=56
    __dict__ size=769392 flat=112
        [V] logger: <RootLogger root (DEBUG)> size=760784 flat=56
        [V] some_large_list: ([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, .... 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],) size=8152 flat=56
        [V] anotherlist: ([1, 1, 1, 1, 1],) size=160 flat=56
        [K] some_large_list size=64 flat=64
        [K] anotherlist size=64 flat=64
        [K] logger size=56 flat=56
    __class__ size=0 flat=0
```

Proposed output:

```python
<tmp.MyObject object at 0x7f7bcf3b0710> size=8664 flat=56
    __dict__ size=8608 flat=112
        [V] some_large_list: ([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, .... 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],) size=8152 flat=56
        [V] anotherlist: ([1, 1, 1, 1, 1],) size=160 flat=56
        [K] some_large_list size=64 flat=64
        [K] anotherlist size=64 flat=64
        [K] logger size=56 flat=56
        [V] logger: <RootLogger root (DEBUG)> skipped
    __class__ size=0 flat=0
```

**Comment by mrJean1** [comment]
Generally, using private** functions or methods is not advised.  Will investigate and reply soon.

**) with names starting with an underscore.

**Comment by Bootstrap360** [comment]
Yes, I would agree. I think there should be an key word argument added to
the function call so you could call with 'ignore_classes=(logging.Logger)'

**Comment by mrJean1** [comment]
There is an way to ignore certain classes (or types) from sizing, see the method `Asizer. exclude_types`.

Try this: create an instance of `Asizer`, use method `.exclude_types` to specify the classes to be ignored and then invoke the `.asizeof` method.

**Comment by Bootstrap360** [comment]
Using .exclude_types worked for me
