### ISSUE TITLE
ModuleNotFoundError: No module named 'resource'

### ISSUE THREAD

**Issue by deisi** [pympler/pympler#133]
I installed pympler 1.0 from pip under python 3.9 on windows and get the above error message if I:

```python
In [4]: import pympler.process
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-4-a3331b726095> in <module>
----> 1 import pympler.process

D:\Projects\CESPT\venv\lib\site-packages\pympler\process.py in <module>
     27 from pympler.util.stringutils import pp
     28
---> 29 from resource import getpagesize
     30
     31
```

Python version: `'3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)]'`

To me it looks like something is missing but I have no clue why and how.

**Comment by Pankrat** [comment]
The resource module is only available on Unix-based systems. This is a regression in Pympler 1.0 and I'll try to fix this ASAP. Older versions (0.9) should still work on Windows.

Thanks for the report!

**Comment by Pankrat** [comment]
This should be fixed in Pympler 1.0.1. Can you confirm that `import pympler.process` now works for you?

**Comment by deisi** [comment]
Year works know: Thank you very much. The only "issue" i had is that I had already installed `pywin32==225` but reseived a warning 
`WARNING:root:Please install pywin32` when using pympler on Windows.
After updating to `pywin32==303` the warning was gone. Thus I assume, there is a specific minimal version of pywin needed for this to work. Would be nice if the warning would reflect that.

**Comment by Pankrat** [comment]
Thanks for the feedback.

I've tested the pywin32 issue on Windows 10 and had the same error with
version 225. Version 226 and up worked. 225 doesn't seem to work on my
system at all (can't find the DLL).

Now that we're using setuptools, it might be a good idea to make pywin32 a
platform specific dependency (and pin it to ">225").

Malte Deiseroth ***@***.***> schrieb am Fr., 24. Dez. 2021,
07:09:
