### ISSUE TITLE
"error: option --user not recognized" when trying to do a user-specific installation

### ISSUE THREAD

**Issue by geo909** [pympler/pympler#15]
Hello,

I am trying to use pympler 0.3.1 in my school's server computer, which has python 2.6.6. I see the following in Pympler's README file:

> 2.b) For a user-specific** installation run:
>
>    python setup.py --user install

So I first run `python setup.py try` which is succesful (output here:http://pastebin.com/V3FCi5JV).
Then I run

```
[x@y Pympler-0.3.1]$ python setup.py build
running build
running build_py
```
But in the last step I have an error:
```
[x@y Pympler-0.3.1]$ python setup.py --user install
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: option --user not recognized

```

Any ideas why I get this error? 

Some info about the system:
```
LSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID: Scientific
Description:    Scientific Linux release 6.6 (Carbon)
Release:        6.6
Codename:       Carbon
```
```
[x@y Pympler-0.3.1]$ python --version
Python 2.6.6
```

**Comment by Pankrat** [comment]
I believe that's a documentation error and should read

`python setup.py install --user`

Does this work for you?

**Comment by geo909** [comment]
Yes, that works, thank you!

**Comment by rebeen** [comment]
I need to use icp but I dont how to call icp function what I did is 
import pcl
pcl.registration.icp(x,y)
please could you tell me how to call this method to align two 2D array
