### ISSUE TITLE
asizeof() gives incorrect values if list has the same items

### ISSUE THREAD

**Issue by NKMR6194** [pympler/pympler#16]
Hello, contributions.

I met the situation, such as:
```
Python 3.4.1 (default, Oct 15 2014, 13:28:30) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pympler.asizeof import asizeof
>>> asizeof([1, 2, 3])
184
>>> asizeof([1, 1, 2])
152
```

I use ea8c2bd9a310647e74304ae6e64cf2c2839d5632

I expected that `asizeof([1, 2, 3])` and `asizeof([1, 1, 2])` give the same values.
Is it specification ? or bug?
Attention : I'm python biginner.

**Comment by Pankrat** [comment]
`asizeof` does recursive sizing and only counts an object once if it is encountered multiple times in the reference tree. This is a bit misleading in your example but if you check with `id` you should see that the first two elements in the second list actually point to the same object (memory location in CPython AFAIK):

```
>>> [id(x) for x in [1,2,3]]
[18637144, 18637120, 18637096]
>>> [id(x) for x in [1,1,2]]
[18637144, 18637144, 18637120]
```

Does this help?

**Comment by Pankrat** [comment]
More information here: http://stackoverflow.com/a/3402717/63392

**Comment by NKMR6194** [comment]
Hello, @Pankrat 

Thanks a lot!
I've found well in your help.
