### ISSUE TITLE
non-free Highcharts JS is preventing Pympler from inclusion in Fedora

### ISSUE THREAD

**Issue by rathann** [pympler/pympler#17]
Dear developers,
please replace pympler/templates/highcharts.js with an alternative that has a free license. Otherwise Pympler cannot be submitted for inclusion in Fedora, which I'm trying to do.

See https://fedoraproject.org/wiki/Licensing:Main#Bad_Licenses_3 .

**Comment by Pankrat** [comment]
AFAICS we only use highcharts for rendering stacked bar charts for the class tracker. Should be be rather easy to replace it with something else.

Candidates:

http://d3js.org/ (BSD)
http://www.flotcharts.org/ (MIT)

**Comment by Pankrat** [comment]
Highcharts has now been replaced by flot (now on master).

**Comment by rathann** [comment]
Thank you, this enables Pympler to be packaged for Fedora. Are there any plans for the next release? If it's not planned soon, I'll simply apply the patches from git to the latest release tarball.

**Comment by Pankrat** [comment]
I've just uploaded 0.4.1 including the change. Thanks for raising the issue.
