### ISSUE TITLE
asizeof seems to ignore private __attr style variables within slots

### ISSUE THREAD

**Issue by ddodt** [pympler/pympler#20]
the `_dir2` routine fails to recognize slot attributes in `__attr` private variable style, which are mangled as `_<ClassName>__attr` by python

adding

                    if a[:2]=="__" : a= '_'+c.__name__+a

as line 354, seems to fix issue for me.
[this isn't displayed correctly I compare the first to chars to 'underscore''underscore' and if true use the c name attribute to emulate the mangling done by python. And yeah I guess this is, because this is not the place for code, but I'm not a regular, and would just like to document a bug and a one-line fix.]

**Comment by Pankrat** [comment]
Thanks for the report. I'll check/integrate your fix when I got more time some time next week.

**Comment by Pankrat** [comment]
Fixed in master. Thanks for the report and fix!
