### ISSUE TITLE
AttributeError: __flags__ using muppy

### ISSUE THREAD

**Issue by jmilloy** [pympler/pympler#24]
I confirmed that I can use muppy or a tracker with the expected results in a simple case. But when I import my library, I get an `AttributeError` when using muppy. It is not informative enough for me to figure out what aspect of my library is causing the problem.

```
from pympler import muppy
import <my library>
objs = muppy.get_objects()
```

This code gives the following exception

```
Traceback (most recent call last):
  File "/home/jmilloy/test.py", line 5, in <module>
    objs = muppy.get_objects()
  File "/usr/local/lib/python2.7/dist-packages/pympler/muppy.py", line 45, in get_objects
    if not _is_containerobject(ref):
  File "/usr/local/lib/python2.7/dist-packages/pympler/muppy.py", line 246, in _is_containerobject
    if type(o).__flags__ & __TPFLAGS_HAVE_GC == 0:
AttributeError: __flags__
```

You won't be able to reproduce because I can't give you access to my library, but maybe we can figure out what's causing it. Have you seen this before?

**Comment by Pankrat** [comment]
I haven't seen this yet. Which exact version of Python (and Pympler) are you using?

It would be interesting to know which kind of object will raise the `AttributeError`. If you could catch the error in `_is_containerobject` and log `repr(o)` and `type(o)` this might help figuring out how to fix this (whether to return `True` or `False` in this case).

Thanks for the report.

**Comment by jmilloy** [comment]
Here you go.

```
ipdb> type(o)
<type 'vtkclass'>
ipdb> repr(o)
'<vtkclass vtkInfovisPython.vtkCircularLayoutStrategy>'
```

**Comment by Pankrat** [comment]
Thanks - that helps. This should now be fixed on master. Please re-open the ticket if it still doesn't work.

**Comment by jmilloy** [comment]
Cool, thanks!
