### ISSUE TITLE
pympler segfault when aerospike loaded

### ISSUE THREAD

**Issue by tigran-a** [pympler/pympler#29]
Hi, crossposting this issue https://github.com/aerospike/aerospike-client-python/issues/106 here: 

In short:  pip install aerospike pympler, then  
```
In [1]: from pympler import tracker
In [2]: import aerospike
In [3]: tr = tracker.SummaryTracker()
Segmentation fault (core dumped)
```

**Comment by Pankrat** [comment]
I'll close the ticket as this has been fixed upstream and AFAICT is not caused by a bug in Pympler. Please reopen if the problem persists.
