### ISSUE TITLE
Pympler django integration doesn't work with django 1.9

### ISSUE THREAD

**Issue by benjyw** [pympler/pympler#31]
I've submitted a fix at https://github.com/pympler/pympler/pull/30. 

Thanks!

**Comment by Pankrat** [comment]
Thanks for the fix!

**Comment by benjyw** [comment]
Thanks for the quick turnaround! Roughly when do you think there will be a pypi release including this commit?

**Comment by Pankrat** [comment]
I want to get the tests passing for all supported Python versions and then push out a bugfix update. I think end of March is realistic.
