### ISSUE TITLE
asizeof does not properly size namedtuples

### ISSUE THREAD

**Issue by Paul-E** [pympler/pympler#35]
If I run asizeof on a normal tuple, I get the following:

```
>>> from pympler import asizeof
>>> asizeof.asizeof(list(range(1000)), "foo")
41160
```

If I create a named tuple and run asizeof on that object, I don't get the correct size:

```
>>> from pympler import asizeof
>>> from collections import namedtuple
>>> TestTuple = namedtuple("TestTuple", ["a", "b"])
>>> asizeof.asizeof(TestTuple(list(range(1000)), "foo"))
120
```

I believe asizeof should be returning roughly the same values for these calls.

This output was produced on Python 3.4 using pympler 0.4.3. Perhaps this is related to #10?

**Comment by kwlzn** [comment]
+1

**Comment by Pankrat** [comment]
Thanks for the report and the fix!
