### ISSUE TITLE
asizeof does not properly size numpy arrays

### ISSUE THREAD

**Issue by Paul-E** [pympler/pympler#36]
Although numpy is not a part of the python standard library, it is a part of many python developer's standard toolkits. Therefore it seems like it would be useful to properly size numpy arrays. Currently asizeof does not properly size numpy arrays. eg:

```
>>> import numpy as np
>>> from pympler import asizeof
>>> example = np.arange(1000)
>>> asizeof.asizeof(example)
80
```
Clearly, an array of 1000 values should take more than 80 bytes of memory.
Fortunately numpy arrays have an "nbytes" property that indicates their size, thus

```
>>> example.nbytes
8000
```
It may be possible to get an accurate idea of numpy array memory usage using this property.

I ran these commands in Python 3.4 with pympler 0.4.3

**Comment by isaacmasher** [comment]
Hi,

I was able to solve the problem by editing the pympler source.  In asizeof.py, edit the `flat()` method to read as follows:

`def flat(self, obj, mask=0):
    '''Return the aligned flat size.
    '''
    s = self.base
    if isinstance(obj,np.ndarray):
        s = obj.nbytes
    else:
        if self.leng and self.item > 0:  # include items
            s += self.leng(obj) * self.item
        if _getsizeof:  # _getsizeof prevails
            s = _getsizeof(obj, s)
    if mask:  # align
        s = (s + mask) & ~mask
    return s`

Worked for me, but I am by no means an expert and this may not be a general solution.

**Comment by Pankrat** [comment]
Numpy array sizing works correctly for me (Numpy version 1.11 on Linux):

```
>>> asizeof.asizeof(example)
8096
```

Which OS and Numpy version are you using?

**Comment by Paul-E** [comment]
I can't seem to reproduce this error on any of my machines (Ubuntu 16.04, Python 3.5, Numpy 1.11.0) any more. This may just be an issue in Ubuntu 15.10. Perhaps an update in python or numpy changed this? I will close this bug. If anyone can reproduce the error on their machine it would be best they open a new bug so they can provide details.

**Comment by isaacmasher** [comment]
I'm using Windows 7 Professional (32bit Anaconda Python) and numpy 1.11.1
