### ISSUE TITLE
use system bottle

### ISSUE THREAD

**Issue by rathann** [pympler/pympler#37]
Pympler includes bottle (in `pympler/util/bottle.py`). I patched it to use system-wide bottle module and it seems to work fine (at least the tests pass). Please consider adding support for using the system version of bottle.

**Comment by Pankrat** [comment]
Pympler currently has no package dependencies and I'd like to keep it that way unless there's a good reason to change that. Does the embedded version of bottle create any problem for your use case?

**Comment by rathann** [comment]
Yes, by its very existence. Fedora aims to have just one system-wide copy of every library mostly for security reasons (we can issue a security update for one library package and all consumers will benefit from the security update).

**Comment by Pankrat** [comment]
I see. We could prefer the installed version of bottle over the vendored version and use the latter only as a fallback (see the referenced commit 854c4e2).

If that's not good enough for the packaging policy, you could also omit bottle.py when packaging Pympler for Fedora. Let me know, If there's anything that can be done inside Pympler for making the packaging easier.

By the way, we do not inject the vendored version of bottle into the global namespace - this means that only Pympler will use the embedded version of bottle.

**Comment by rathann** [comment]
That's perfect, thank you very much. The policy in question is here: https://fedoraproject.org/wiki/Packaging:Guidelines#Bundling_and_Duplication_of_system_libraries and here: https://fedoraproject.org/wiki/Bundled_Libraries , by the way. Debian has a similar policy, too: https://www.debian.org/doc/debian-policy/ch-source.html#s-embeddedfiles .

**Comment by Pankrat** [comment]
Pympler 0.5 now prefers the system version of bottle and only falls back to the vendored version if bottle is not installed. I'll close the issue. Please reopen if it's not working as expected.

Thanks for the report and following up on the issue!
