### ISSUE TITLE
pympler incompatible with tensorflow

### ISSUE THREAD

**Issue by vladfi1** [pympler/pympler#41]
It seems that pympler doesn't work with [tensorflow](https://www.tensorflow.org/), a popular deep learning toolkit. I suspect this has something to do with tensorflow being a python binding to a C++ implementation.

```
>>> import tensorflow
>>> from pympler.tracker import SummaryTracker
>>> tracker = SummaryTracker()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vlad/.local/lib/python3.5/site-packages/pympler/tracker.py", line 45, in __init__
    self.s0 = summary.summarize(muppy.get_objects())
  File "/home/vlad/.local/lib/python3.5/site-packages/pympler/muppy.py", line 37, in get_objects
    tmp = [o for o in tmp if not isframe(o)]
  File "/home/vlad/.local/lib/python3.5/site-packages/pympler/muppy.py", line 37, in <listcomp>
    tmp = [o for o in tmp if not isframe(o)]
  File "/usr/lib/python3.5/inspect.py", line 239, in isframe
    return isinstance(object, types.FrameType)
ReferenceError: weakly-referenced object no longer exists
```

**Comment by dm-mch** [comment]
The same issue

**Comment by sriramrajendiran** [comment]
facing the same issue

**Comment by Pankrat** [comment]
I can reproduce this issue on Python 3.5 (works fine on Python 2.7). 

I have a potential fix but I'm not yet sure whether it's the correct way to handle that problem.

**Comment by kingspp** [comment]
@Pankrat Can you pls post the fix? Or give an idea?

**Comment by Pankrat** [comment]
@kingspp I've committed a potential fix to the Pympler master branch. Could you try that?

**Comment by Pankrat** [comment]
The fix is in Pympler 0.5. Could you check if upgrading to Pympler 0.5 fixes the issue?

**Comment by kingspp** [comment]
Got it working. Thanks

**Comment by Pankrat** [comment]
Thanks for checking!
