### ISSUE TITLE
installation get stucks when performing tests

### ISSUE THREAD

**Issue by Trophime** [pympler/pympler#46]
Hi,
I would like to use pympler and eventually package it for Debian/Ubuntu.
Trying to create the package, it gets stuck while performing tests:
```
Test if reference cycles can be viewed. ...
```

does this require something special?
Best

**Comment by Pankrat** [comment]
This might indicate that the web interface is not starting up properly - I've now added a timeout in the test so that at least the test is not hanging.

Could you tell me which version of Pympler, Python and OS you're running and whether Bottle is installed either via pip or your package manager?

```bash
pip list | grep bottle
apt show -a python-bottle 
dpkg -s python-bottle
```

**Comment by Trophime** [comment]
Hi,
with the latest release everything is fine even if Bottle is not installed.
Bottle is only required for testing purposes?

Thanks

**Comment by Pankrat** [comment]
Thanks for checking. 

Bottle is used for the Pympler web interface - it is included in the source distribution but can be removed when packaging it for distributions which don't allow including third party libraries. In this case, bottle needs to be installed separately.
