### ISSUE TITLE
REL: new release?

### ISSUE THREAD

**Issue by CJ-Wright** [pympler/pympler#49]
Would it be possible to put out a new release?
It seems some bugs were fixed that would be very helpful to have tagged.

**Comment by Pankrat** [comment]
Yes, this is long overdue. I'll see if I can push a new version to PyPI later this weekend.

**Comment by CJ-Wright** [comment]
If you can just tag it on github I can build it on conda-forge.

**Comment by Pankrat** [comment]
Pympler 0.5 has just been released.
