### ISSUE TITLE
Wrong results when measuring object that uses __slots__?

### ISSUE THREAD

**Issue by ivoanjo** [pympler/pympler#69]
Hello there, and thanks for Pympler!

While doing a few experiments on a class that uses `__slots__` to reduce memory footprint I ran into a few unexpected results.

Testcase:

```python
import sys
print(sys.version)
from pympler import asizeof

SLOTS = ("foo", "bar")

class Foo(object):
  __slots__ = SLOTS

  def __init__(self):
    self.foo = SLOTS
    self.bar = SLOTS

print(asizeof.asized(Foo(), detail=1).format())
print("Same object? " + str(Foo().__slots__ is SLOTS))
```

Results:

```
3.6.5 (default, Jun 20 2018, 09:33:17) 
[GCC 5.4.0 20160609]
<__main__.Foo object at 0x7f143841ac88> size=304 flat=56
    foo size=176 flat=64
    __slots__ size=72 flat=72
    __class__ size=0 flat=0
    bar size=0 flat=0
Same object? True
```

Three things seem to be wrong in this case:

* the flat size of `__slots__` is 8 bytes more than the object itself
* the total size of the `Foo` instance does not account for the fact that `foo` and `__slots__` are pointing at the same object
* the flat size of `__slots__` is shown to be the same as the size

Thus, whereas I would expect in this case the total size to be 56 + 176, pympler reports it as 56 + 176 + 72.

I was able to validate similar results with Python 2.7, so it doesn't seem to be something that may be off in any specific version.

Is this a pympler bug, or am I missing some important detail on how `__slots__` are actually implemented that causes this?

**Comment by mrJean1** [comment]
A few, initial things.  (a) Sizes differ for 32- and 64-bit, (b) sizes may have been rounded up to the next multiple of 8 bytes, and (c) in Python 2, `__slots__` require a new-style class, like `class Foo(object): ..`.  Need to investigate this further and will reply more then.

**Comment by ivoanjo** [comment]
Thanks for the quick reply! Indeed, I added the `(object)` when tested on Python 2 and then copy/pasted the old version of the code ;)

Let me know if I can provide more information for the investigation!

**Comment by mrJean1** [comment]
All sizes seem correct when compared to system.getsizeof, one exception the size of the __slots__ in the Foo() instance.  The additional 8 bytes (compared to the size of SLOTS) is due to the following assumption inside function asizeof._dir2 ...

            # assume __slots__ tuple/list
            # is holding the attr values

The instance specific __slots__ values are assumed to be stored in a tuple.  The instance must hold the reference (i.e. pointer) to that tuple, the additional 8 bytes (for 64-bit).

Perhaps that assumption is incorrect and should be revisited and verified against the C implementation of __slots__-based instances.  But the difference will at be 4 or 8 bytes or a at most 2-3%.

Keep in mind, the ‘a’ in ‘asizeof’, ‘asized’, etc. means approximate, not accurate ;).  Hope this makes sense

**Comment by mrJean1** [comment]
All sizes seem correct when compared to system.getsizeof, one exception the size of the `__slots__` in the `Foo()` instance.

The additional 8 bytes (compared to the size of `SLOTS`) are due to the following assumption inside function `asizeof._dir2` [on line 433 ff](https://github.com/ActiveState/code/blob/master/recipes/Python/546530_Size_of_Python_objects_revised/recipe-546530.py) ... _assume `__slots__` tuple/list is holding the attr values_ ... meaning the instance-specific `__slots__` values are _assumed_ to be stored in a tuple (or list) and that's how `__slots__` are sized: as a separate tuple (or list) plus a reference to that tuple (or list).

Perhaps that assumption and/or `__slots__` sizing this way is incorrect and should be revisited.  Hope this helps.

**Comment by ivoanjo** [comment]
I was experimenting a bit more and the current measurement for `__slots__` is also incorrect when you have multiple instances:

```python
import sys
print(sys.version)
from pympler import asizeof

SLOTS = ("foo", "bar")

class Foo(object):
  __slots__ = SLOTS

  def __init__(self):
    self.foo = SLOTS
    self.bar = SLOTS

print(asizeof.asized([Foo(), Foo()], detail=2).format())
```

which results in:

```
3.6.5 (default, Jun 20 2018, 09:33:17) 
[GCC 5.4.0 20160609]
[<__main__.Foo object at 0x7f573ca97c5...._main__.Foo object at 0x7f573ca97c88>] size=512 flat=80
    <__main__.Foo object at 0x7f573ca97c50> size=304 flat=56
        foo size=176 flat=64
        __slots__ size=72 flat=72
        __class__ size=0 flat=0
        bar size=0 flat=0
    <__main__.Foo object at 0x7f573ca97c88> size=128 flat=56
        __slots__ size=72 flat=72
        __class__ size=0 flat=0
        foo size=0 flat=0
        bar size=0 flat=0
```

where we can see that unlike with normal arguments, the `__slots__` are again counted for every instance, instead of being counted as a pointer to the same `SLOTS` object and thus only once. Compare that with the normal slots where the reference to `SLOTS` is only counted once, even though it is repeated 4 times -- for `foo` and `bar` on the two objects.

**Comment by mrJean1** [comment]
That is another artifact of the current `__slots__` sizing.  However, how likely is it that multiple instances have `__slots__` with the exact same contents?  In any case, this remains an issue to be investigated further.

**Comment by ivoanjo** [comment]
> However, how likely is it that multiple instances all have __slots__ with the exact same contents in all __slots__?

100% likely -- this is what `__slots__` is for, right? You declare the fields the class will have as a tuple/list, and Python uses that instead or in addition to a `__dict__`.

**Comment by mrJean1** [comment]
Well, if all `__slots__` in all instances have the same value why use `__slots__` to begin with?  A singleton would be fine.

In any case, I’ll try to find a way to handle that particular scenario better.  The key question is how are `__slots__` values being stored in an instance?  In a tuple-like container? Inside the instance object itself?  Some other way?  And, if 2 instances have the same  `__slots__` are those really shared?  The  `__slots__` values will , but not the `__slots__` tuple-like container, I assume.

Btw, only the `__slots__` (i.e. that tuple-like container) are sized for each instance, not the contents of each `__slots__`   The latter are sized once for the same value.

**Comment by ivoanjo** [comment]
> Well, if all `__slots__` in all instances have the same value why use `__slots__` to begin with? A singleton would be fine.

This is the documented way of using `__slots__`, see for instance the "Saving Space with the __slots__ Class Attribute" section in this book <https://books.google.ie/books?id=bIZHCgAAQBAJ&lpg=PP1&dq=fluent%20python&pg=PT364#v=onepage&q=Saving%20Space%20with%20the&f=false>. 😄

> In any case, I’ll try to find a way to handle that particular scenario better. The key question is how are `__slots__` values being stored in an instance? In a tuple-like container? Inside the instance object itself? Some other way? And, if 2 instances have the same `__slots__` are those really shared? The `__slots__` values will , but not the `__slots__` tuple-like container, I assume.

My understanding is that when you use `__slots__` then the class instance variables are stored directly in the object and not in the `__dict__`, and I think the example above illustrates that: we can see that `foo` and `bar` show up inside the object alongside `__slots__` and `__class__`.

**Comment by mrJean1** [comment]
Glad you mentioned _Fluent Python_, that answers the question where/how `__slots__` instance values are stored.  I’ll need to run a few other test to get to the bottom of this (and fix `asizeof` accordingly).

**Comment by ivoanjo** [comment]
Yes, it looks much better and solves my issue, thanks!

I wouldn't mind if the `__slots__` were counted the first time (e.g. if they just followed the same rules as normal instance variables/slot), but omitting them is also OK for my use.

**Comment by mrJean1** [comment]
Great!

I’ll try to size `__slots___` as part of the `__class__`.  That would make sense, since `__slots__` are defined there.

**Comment by mrJean1** [comment]
After some juggling, the `__slots__` size is reported along with other `__class__`-level attributes.  Note, (a) that is the size of the `__slots__` _definition_ in the `__class__` and (b)  `__class__` attributes are considered _code_ in `asizeof`, meaning keyword argument `code=True` is required to get those sizes.  Example:

```
import sys
print(sys.version)
from pympler import asizeof

FOOS = ("foo",)

class Foo(object):
  __slots__ = FOOS

  def __init__(self):
    self.foo = FOOS

print('Foo: %s' % sys.getsizeof(Foo()))
print(asizeof.asized(Foo, code=True, detail=1).format())
print(asizeof.asized(Foo(), detail=1).format())

BARS = ("foo", "bar")

class Bar(object):
  __slots__ = BARS

  def __init__(self):
    self.foo = BARS
    self.bar = BARS

print('Bar: %s' % sys.getsizeof(Bar()))
print(asizeof.asized(Bar, code=True, detail=1).format())
print(asizeof.asized(Bar(), detail=1).format())
```
Output from Python 2.7.15:

```
% python test_asizeof.py
2.7.15 (v2.7.15:ca079a3ea3, Apr 29 2018, 20:59:26) 
Foo: 56
Foo size=2680 flat=944
    __dict__ size=1504 flat=56
    __slots__ size=104 flat=64
    __mro__ size=72 flat=72
    __name__ size=40 flat=40
    __doc__ size=16 flat=16
    __class__ size=0 flat=0
<__main__.Foo object at 0x108109c58> size=160 flat=56
    foo size=104 flat=64
    __class__ size=0 flat=0
(<__main__.Foo object at 0x108109c58>, <__main__.Foo object at 0x108109c20>) size=288 flat=72
    <__main__.Foo object at 0x108109c58> size=160 flat=56
        foo size=104 flat=64
        __class__ size=0 flat=0
    <__main__.Foo object at 0x108109c20> size=56 flat=56
        __class__ size=0 flat=0
        foo size=0 flat=0
Bar: 64
Bar size=2864 flat=984
    __dict__ size=1600 flat=56
    __slots__ size=152 flat=72
    __mro__ size=72 flat=72
    __name__ size=40 flat=40
    __doc__ size=16 flat=16
    __class__ size=0 flat=0
<__main__.Bar object at 0x108112110> size=216 flat=64
    foo size=152 flat=72
    __class__ size=0 flat=0
    bar size=0 flat=0
(<__main__.Bar object at 0x108112110>, <__main__.Bar object at 0x1081dd990>) size=352 flat=72
    <__main__.Bar object at 0x108112110> size=216 flat=64
        foo size=152 flat=72
        __class__ size=0 flat=0
        bar size=0 flat=0
    <__main__.Bar object at 0x1081dd990> size=64 flat=64
        __class__ size=0 flat=0
        foo size=0 flat=0
        bar size=0 flat=0

```
and Python 3.7.0:

```
% python3 test_asizeof.py
3.7.0 (v3.7.0:1bf9cc5093, Jun 26 2018, 23:26:24) 
Foo: 48
Foo size=2496 flat=888
    __dict__ size=1360 flat=48
    __slots__ size=112 flat=56
    __mro__ size=64 flat=64
    __name__ size=56 flat=56
    __doc__ size=16 flat=16
    __class__ size=0 flat=0
<__main__.Foo object at 0x1103ba258> size=160 flat=48
    foo size=112 flat=56
    __class__ size=0 flat=0
(<__main__.Foo object at 0x1100537f8>, <__main__.Foo object at 0x110053948>) size=272 flat=64
    <__main__.Foo object at 0x1100537f8> size=160 flat=48
        foo size=112 flat=56
        __class__ size=0 flat=0
    <__main__.Foo object at 0x110053948> size=48 flat=48
        __class__ size=0 flat=0
        foo size=0 flat=0
Bar: 56
Bar size=2648 flat=888
    __dict__ size=1448 flat=48
    __slots__ size=176 flat=64
    __mro__ size=64 flat=64
    __name__ size=56 flat=56
    __doc__ size=16 flat=16
    __class__ size=0 flat=0
<__main__.Bar object at 0x110396a90> size=232 flat=56
    foo size=176 flat=64
    __class__ size=0 flat=0
    bar size=0 flat=0
(<__main__.Bar object at 0x11039a128>, <__main__.Bar object at 0x110396a90>) size=352 flat=64
    <__main__.Bar object at 0x11039a128> size=232 flat=56
        foo size=176 flat=64
        __class__ size=0 flat=0
        bar size=0 flat=0
    <__main__.Bar object at 0x110396a90> size=56 flat=56
        __class__ size=0 flat=0
        foo size=0 flat=0
        bar size=0 flat=0

```
Note, the sizes of the `__class__` attributes do not add up to the total size of the class, due to hidden sizes.  Use keyword `detail=2` or higher to get more _code_ sizes, like the _code_ size of `methods`.

**Comment by mrJean1** [comment]
Filed pull request for the modified `asizeof.py` file.

**Comment by ivoanjo** [comment]
I actually meant something slightly different, but the impact is rather small: I was thinking that `__slots__` could still show up in each individual objects, but they would only be counted once (same as with other fields), e.g. something like:

```python
import sys
print(sys.version)
from pympler import asizeof

FOOS = ("foo",)

class Foo(object):
  __slots__ = FOOS

  def __init__(self):
    self.foo = 1

print('Foo: %s' % sys.getsizeof(Foo()))
print(asizeof.asized(Foo(), detail=1).format())
```

imaginary output:

```
FAKE OUTPUT (default, Jun 20 2018, 09:33:17) 
<__main__.Foo object at 0x7f143841ac88> size=256 flat=56
    foo size=24 flat=24
    __slots__ size=176 flat=64 # <-- size of slots
    __class__ size=0 flat=0
```

but then going back to my second example:

```python
import sys
print(sys.version)
from pympler import asizeof

SLOTS = ("foo", "bar")

class Foo(object):
  __slots__ = SLOTS

  def __init__(self):
    self.foo = SLOTS
    self.bar = SLOTS

print(asizeof.asized([Foo(), Foo()], detail=2).format())
```

the result would be:

```
FAKE OUTPUT (default, Jun 20 2018, 09:33:17) 
[<__main__.Foo object at 0x7f573ca97c5...._main__.Foo object at 0x7f573ca97c88>] size=512 flat=80
    <__main__.Foo object at 0x7f573ca97c50> size=304 flat=56
        foo size=176 flat=64
        __slots__ size=0 flat=0  # <-- size already accounted for in foo
        __class__ size=0 flat=0
        bar size=0 flat=0
    <__main__.Foo object at 0x7f573ca97c88> size=128 flat=56
        __slots__ size=0 flat=0
        __class__ size=0 flat=0
        foo size=0 flat=0
        bar size=0 flat=0
```

But the current approach is fine for me too. Thanks for opening #70 ! :tada: :+1: 

(P.s.: Thanks for looking into this! And also, did you know that if you guard your code blocks with the programming language, you get code highlighting? e.g. use ` ```python ` instead of just ` ``` ` to start the code block)

**Comment by mrJean1** [comment]
Four things:

a) The `__slots__` attribute only shows the size of the tuple-like `__slots__` space, like `asizeof` did before ... by creating a tuple on the fly.

b) To size `__slots__` only once would require using the exact sample tuple (with the same `id`) for all instances of a class.  That could easily be done by using the class-level `__slots__` instead of an on-the-fly tuple.

c) However, the `__slots__` size will be included in the total size of the first instance of a class, effectively _-and incorrectly-_ counting that size twice.  Avoiding the double count would require gymnastics across `asizeof`, which is already too large, too complex.

d) `__slots__` are a class-level attribute.  Therefore, the proper place to report the size of tuple-like `__slots__` storage is when sizing the class, not the instance.

**Comment by mrJean1** [comment]
Just fixed the tests for `asizeof` after the `__slots__` changes.  The failing test assumed that `__slots__` would be one of the items returned by function `asizeof.refs(a__slots__instance)`.  That is no longer the case, the `__slots__` definition is no longer part of `refs`.

There may be other `__slots__` usecases depending on the `__slots__` to be part of the refs result.  Those cases will fail now.

**Comment by ivoanjo** [comment]
Fair enough. Indeed the `__slots__` are more of a class-level attribute and it cannot be changed on instances after they are created so yeah it probably is better to have them on the class, not on the instance. :+1:

Interestingly, I was trying to "break" Python but it actually ends up behaving in a rather weird way:

```python
import sys
print(sys.version)

class Foo(object):
	  __slots__ = ("hello",)

	  def __init__(self):
	  	  self.hello = "howdy"

Foo.__slots__ = ("world",)

f1 = Foo()
print(dir(f1))

print(f1.hello)
print(Foo.__slots__)
```

The result is not what I was expecting:

```
3.6.3 (default, Oct  3 2017, 21:45:48) 
[GCC 7.2.0]
['__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__slots__', '__str__', '__subclasshook__', 'hello']
howdy
('world',)
```

So it seems like you can change the `__slots__` on the class after it is created, but Python will ignore your change when creating new instances.

So in this very specific case the memory accounting will probably be off because `Foo.__slots__` is actually not the same as `f1.__slots__` ;)
But we may just not want to care about such corner cases.
